ref: sfaisal/${basearch}/kubernetesos/master
include: 
- fedora-coreos.yaml

releasever: "1"

packages:
- kubernetes-master
- etcd

repos:
- fedora
- fedora-coreos-pool

postprocess:
    # remove the "fedora" ostree remote
    - |
      #!/usr/bin/env bash
      set -xeuo pipefail
      rm /etc/ostree/remotes.d/fedora.conf
      sed 's/SELINUX=enforcing/SELINUX=permissive/' /etc/selinux/config
