ref: sfaisal/${basearch}/kubernetesos/worker
include: 
- fedora-coreos.yaml

releasever: "1"

packages:
- kubernetes-node
- socat
- conntrack
- ipset
- containernetworking-plugins

repos:
- fedora
- fedora-coreos-pool

postprocess:
    # remove the "fedora" ostree remote
    - |
      #!/usr/bin/env bash
      set -xeuo pipefail
      rm /etc/ostree/remotes.d/fedora.conf
      sed -i 's/SELINUX=enforcing/SELINUX=permissive/g' /etc/selinux/config
      sudo swapoff -a
